### ISSUE TITLE
Opening the DialogTextViewer

### ISSUE THREAD

**Issue by MartijnKaijser** [Black09/Xperience1080#2]
I was working a a new feature for Artwork Downloader
http://forum.xbmc.org/showpost.php?p=980094&postcount=132

and I was testing different skins out on how that would look. Because your skins works somewhat different than others i would like to try and fixed it.

The first problem I had was that you don't have a Label in you textviewer.
ERROR: Artwork Downloader: 'xbmcgui.ControlGroup' object has no attribute 'setLabel'

No problem because that's just a try...except: pass

The other issue now is that you shift in the textviewer but the original window stays.
http://img52.imageshack.us/img52/7294/screenshot078b.png

How can we solve it so it looks readable/normal?

**Comment by Black09** [comment]
I just add a different layout for the textviewer. The current layout is only for addon info.

**Comment by MartijnKaijser** [comment]
This one is also for the changelog?

Edit:
Maybe i can shift the windows away like you do in add-on info?

**Comment by Black09** [comment]
Yes TextViewer is used for changelog. I think you shouldn't do anything, I'll provide a different layout for the dialog.

**Comment by MartijnKaijser** [comment]
Thanks :)
If you want to try it just grab the latest master branch code and run the add-on couple of seconds and then cancel it. Then you will get the report button.
Let me know if there's any issue

**Comment by Black09** [comment]
Should work now. :)

**Comment by MartijnKaijser** [comment]
Perfect :)
