### ISSUE TITLE
Colorpicker note as missing but exist

### ISSUE THREAD

**Issue by Biofx** [Black09/Xperience1080#29]
Since this morning i dont see any art poster . The menu says colorpicker is missing but its alleready installed. 

I try to refresh all art but thats change nothing.

Other skins like aeon nox shows poster correctly. 

How can i fixe It?

Thks

**Comment by Black09** [comment]
Colorpicker, what? Absolutely no idea, this is no skin issue.

**Comment by Biofx** [comment]
Its ok i remove all, and reinstalll skin. It works perfectly....;))
