### ISSUE TITLE
discs not autoplaying

### ISSUE THREAD

**Issue by bassic** [Black09/Xperience1080#31]
Audio cds and dvds don't autoplay. Seems to work ok with confluence.

**Comment by Black09** [comment]
Working fine here... also it's very unlikely that this could be a skin problem because auto play is handled by XBMC and not by the skin.

**Comment by bassic** [comment]
Strange as it works for me with confluence. I’ve got a couple of other odd issues so maybe its time for a complete re-install.

Thanks Black,

Ralph

**Comment by Black09** [comment]
If you've done a reinstall and it's still not working, please post a debug log.

**Comment by bassic** [comment]
I did a re-install but still no luck. Here's a log of it working with confluence and a log of it not working with xperience. 

No changes other than swapping the skin, just starting xbmc, inserting  a cd, ejecting and shutdown.

Confluence log - http://xbmclogs.com/show.php?id=32277 

Xperience log - http://xbmclogs.com/show.php?id=32278

A little more info.... when debug is on, the osd showing cpu utilisation hangs for about ten seconds with experience when I insert the cd. XBMC seems to become unresponsive to the remote during that time too.

I'm not seeing any way to play a cd from within experience, not even manually. Should there be a menu item appearing when I put a cd in?

Hopefully I'm just missing something obvious, wouldn't be the first time ;)

Cheers

**Comment by Black09** [comment]
The only thing I see is that is says "CWinEventsWin32::WndProc: Drive E:\ Media has arrived" in the Confluence log and "CWinEventsWin32::WndProc: Drive E:\ Media was removed" (before the 10s lag with no debug output at all) in the Xperience log. I have absolutely no idea why it's not working. Only thing I could think of is the skin widgets add-on because it subclasses the player instance... try to disable it, restart XBMC and see if it works.

PS: You can play dvd's and audio cd's in the movie tab on home.

**Comment by bassic** [comment]
Well here's one of the stranger things I've seen.... it works perfectly for me, but only if I have the skin settings menu open.

If I go into settings -> skin and have any one of the screens open and insert a cd, it works every time. If I exit the skin settings dialogues it stops working.

Here's a log of it working - http://xbmclogs.com/show.php?id=32568

Re your PS Black, I can't see a way to manually play cd's from the home screen. I've got a new movies tile there, can't see any way to use that???

Thanks

oh forgot, disabled the skin widgets and restarted, didn't fix it.

**Comment by Black09** [comment]
Did you try without skin widgets? I'm afraid I can't help you much with this... there are sometimes some strange errors, maybe it's an animation somewhere or something else which brakes it in some special situations but I have no idea.

In the movie tab (the new movies tile is on the home tab) is a disc icon instead of the add-ons icon as soon as you insert a cd/dvd. If you select the tile, cd/dvd will start playing.

**Comment by bassic** [comment]
Disabling the skin widgets didn't help I'm afraid.

I don't get the disc icon when I insert a cd. Makes sense I guess as it doesn't seem to recognize the presence of a disk. 

Oh well, just one of those things I suppose, cheers.

**Comment by Black09** [comment]
If it's working in the settings window, does it work anywhere else? If you are in the library or the file manager for example. If the problem exists only on the home screen, could you try inserting a disc when you are on a tab where no AlarmClock is running, e.g. apps, weather or settings.

**Comment by bassic** [comment]
Well look at that. The only place it seems not to work is on the initial screen you get when you start xbmc. If I select livetv/movies/tvshows/weather/apps/settings and insert a cd it works. 

If I then exit back to the metro screen while the cd is playing the Audio CD tile is there instead of the add-ons one just as you said.

Seems to be only the initial screen that doesn't want to behave. I can live with that if it's just picking on me. ;)

**Comment by bassic** [comment]
I noticed something today that might be a clue with this issue.....

When I insert a disc the icon on the Movie tab doesn't change to allow me to play the cd/dvd. But if I go to the Music tab, select Files and then exit back to the main screen, the disc icon is there as it should be.

It only does this if I access Files via the Music tab.If I access files from the TV Show or Movies tabs it doesn't work.

This is with win8/xbmc 12.1/todays xperience github version.

Cheers.

**Comment by Black09** [comment]
So, does this (autoplay) work now after my latest updates or is it still not working?

**Comment by bassic** [comment]
Yep, works fine now. Thanks for the fix!
