### ISSUE TITLE
No polish diacrytics with default fontset.

### ISSUE THREAD

**Issue by marcinant** [Black09/Xperience1080#4]
When set Polish language some characters are not visible with XPCondensed.ttf on Linux Ubuntu 11.10

I edited 1080i/Font.xml and replaced XPCondensed.ttf with Ubuntu-L.ttf and everything looks ok and pretty.

As you also probably know XPCondensed (Segoe Condensed) is copyrighted by Microsoft and should not be distributed.
I don't care because I don't use it anymore and I have deleted them from my hdd, but you should be careful when releasing your absolutely stunning skin.

**Comment by Black09** [comment]
Yes I know that and I'm looking for alternatives. Could you try with [PT Sans Narrow](http://www.fontsquirrel.com/fonts/PT-Sans)? The font is similar to Segoe Condensed, not as good but it's free to use and should work with polish diacrytics.
