### ISSUE TITLE
Wishlist: Watched support in YouTube

### ISSUE THREAD

**Issue by cloakable** [Black09/Xperience1080#43]
I get it in the default Confluence skin, and it even seems to sync using the MySQL database (things I watch on the desktop with Xperience show up with a tickmark on the Raspberry Pi with Confluence).

Would it be possible to show that information using Xperience too? Having those red/green marks next to videos would be handy. :)

**Comment by Black09** [comment]
Should be possible.

**Comment by Black09** [comment]
This is available now. :)
