### ISSUE TITLE
Splash/Loading screen broken

### ISSUE THREAD

**Issue by Begall** [Black09/Xperience1080#45]
Using git from yesterday and a stable build of XBMC Frodo, the loading/splash screen stays on until exit is pressed. This is actually really confusing, as it looks like it has frozen until you think to try pressing exit. 

Edit: And while this is happening the log gets spammed with the following:

19:05:11 T:140180583159680   DEBUG: ExecuteXBMCAction : To SetFocus(11)
19:05:12 T:140180583159680   DEBUG: ExecuteXBMCAction : Translating SetFocus(11)
19:05:12 T:140180583159680   DEBUG: ExecuteXBMCAction : To SetFocus(11)
19:05:13 T:140180583159680   DEBUG: ExecuteXBMCAction : Translating SetFocus(11)
19:05:13 T:140180583159680   DEBUG: ExecuteXBMCAction : To SetFocus(11)

**Comment by Black09** [comment]
Update skin widgets.
