### ISSUE TITLE
Spotlight empty

### ISSUE THREAD

**Issue by Half9** [Black09/Xperience1080#49]
When all movies / tv shows are marked as watch, then there is nothing in the spotlight.

Same with "ongoing tv shows", "new movies" and "new tv shows"

![screenshot000](https://f.cloud.github.com/assets/3681520/188640/b14484f4-7e01-11e2-8c46-11bfaf7b8676.png)

**Comment by Black09** [comment]
Turn off "only unwatched" in the skin widgets settings. And it's clear that ongoing shows is empty if you have watched everything.

**Comment by Half9** [comment]
Thank you. That did the trick.
