### ISSUE TITLE
New Movies Blank or Empty

### ISSUE THREAD

**Issue by rronib** [Black09/Xperience1080#53]
![image](https://f.cloud.github.com/assets/3820820/240492/41b993f2-8920-11e2-8645-9c9778b35cef.jpg)
(

Sorry I know this was posted before but I am so confused to know what to do.

How can I change these logos or banners from blank to something else. I am a beginner at these stuff so I am not sure what to do. All "spotlight", "ongoing TV Shows", "ne tv shows, "featured albums". I have played music, movies on this theme but it is still blank.

Please can you explain in a simple way.

**Comment by Black09** [comment]
Does it say that skin widgets is missing or disabled e.g. on the home tab? If so, install it. If you have installed, check the skin widgets settings.

**Comment by rronib** [comment]
I found out what was the problem. The movies I had were without a picture cover but then I added it. Thanks for your help. Now the problem is when I change a addons logos icon xmbc crashes (looks like a anologe tv without signal). How can I fix that?? Only happens in some addons...

**Comment by Black09** [comment]
No idea but that's not skin specific, you should ask that somewhere in the forum.

**Comment by rronib** [comment]
Ok try ask another place but how can I change the backround to white or something because when I change the backround it is blured or does not show. Can't I change the color of the backround and make the backround not blurred.

**Comment by Black09** [comment]
There is an overlay above the background. You shouldn't modify that or remove it. A full white background doesn't work AT ALL with the skin, so you have to use another skin if you want light backgrounds.

**Comment by rronib** [comment]
By whte I mean like in your video (http://www.youtube.com/watch?v=l_CckS-kxNU) is there a way to do that
![image](https://f.cloud.github.com/assets/3820820/244868/e76481b2-8a70-11e2-9218-6f101071f59f.jpg)

**Comment by Black09** [comment]
Sure but that video is old, the new version won't work with light backgrounds so don't bother trying it.

**Comment by rronib** [comment]
Ok thanks forhelping me, just wanted to know that
