### ISSUE TITLE
Feature Request: Option to merge Infoscreen with controls

### ISSUE THREAD

**Issue by celevra** [Black09/Xperience1080#56]
Hi,

this skin is amazing!
There is only one thing, is it possible to show the info bar with the controls bar at the same time?
if i'm on live tv i have to press "i" to see whats on air and whats next, but it would be perfect if i can see it with the controls.

best regards

**Comment by xhaggi** [comment]
why do you need the controls in this case?

**Comment by celevra** [comment]
if i start livetv (or movies) I have two options.
option one show the controls (pause, next channel, epg and so on)
option two show channel Infos (big channel logo, actual show, next show and so on)

on my remote (boxee remote) I press the standardkey to get the controls.
But to get the info window (option two ;-)) i need to press the "i" key

but i see no reason why this is seperated, i want to press the standard button to get the controls AND the infos
i can try to take photos if that helps to understand ;-)

**Comment by xhaggi** [comment]
@celevra i understand it .. so it's related to your remote .. not enough buttons ;)

**Comment by celevra** [comment]
hehe, im lazy and don't want to push two buttons for a function other themes (like the standard confluence) provide with a singe click ;-)

**Comment by Black09** [comment]
Why don't you map e.g. the ok button to info and the "menu" button below to the controls (or vice versa)? I won't change the current behaviour for now.

**Comment by celevra** [comment]
why should i push two buttons for a function i normaly get in other themes with one button? 
I think controls and info layer should be one
i'm sorry but if there is no way than i have to use other themes because this is a must have for me.
thank you
