### ISSUE TITLE
Getting stuck in featured movie widget

### ISSUE THREAD

**Issue by DanAE111** [Black09/Xperience1080#65]
Sometimes when navigating the main screen scrolling left to right i have ended up getting stuck cycling items in the featured movies thing.

**Comment by Black09** [comment]
Mouse enabled?

**Comment by DanAE111** [comment]
yes, didn't actually realize i could disable it i disabled it now im guessing this fixes the problem?

**Comment by Black09** [comment]
Yes that fixes it. The thing is that the list is never actually focused but if the mouse is enabled, the list could get focus accidentally by a little mouse movement and you are stuck in it.
