### ISSUE TITLE
Artwork downloader latest version (12.0.18) is not working with Xperience 1080 Skin

### ISSUE THREAD

**Issue by vigneshmarthandan** [Black09/Xperience1080#66]
latest version (12.0.18) of Artwork downloader addon is not working with Xperience 1080 Skin. But works with default confluence skin and other skins.

I reckon it is an addon-skin integration issues.

XBMC: Frodo
OS: Mac Snow Leopard
HW: Mac Mini 2010 version

please let me know if additional information is needed.

Note that the previous stable version (12.0.15) of the addon works with xperience 1080

**Comment by Black09** [comment]
This is a problem with AD and it's fixed in 12.0.19 (not pushed to the repo yet). You can download it from github -> https://github.com/XBMC-Addons/script.artwork.downloader
