### ISSUE TITLE
Language update from Transifex

### ISSUE THREAD

**Issue by usrbowe** [Black09/Xperience1080#70]
Hi,

I am curious how often is language strings downloaded from Transifex to this skin? I was told that it's automatically every day. But I translated all strings in Czech language, before two days and nothing happened. Thanks

Link to Czech XBMC Transifex: https://www.transifex.com/projects/p/xbmc-skins/language/cs/

**Comment by Black09** [comment]
No it's not automatically. I have to pull the updates manually and merge them. I don't do it very often at the moment, usually together with a new update.
