### ISSUE TITLE
Now playing

### ISSUE THREAD

**Issue by usrbowe** [Black09/Xperience1080#73]
Hi,
 I have really hard time today, I tried to find some button or menu, which will open "now playing" video from background. I found only this solution, I click on "exit/back" button on my remote, when I was in home screen view, then I get full screen video playing again in foreground. But it's really hard to find this behaviour. It could work like this: Just navigate UP in home screen view (or anywhere else) to info box, where is shown, that there is playing video.

**Comment by Black09** [comment]
Press tab. The action is FullScreen -> http://wiki.xbmc.org/?title=Action_IDs
